[pytest]
pythonpath = app
testpaths =
    app/tests
    app/backtest
    app/feed/tests
    app/feed/backtest
    app/strategy/tests
    app/account/tests
    app/output/tests
    app/output/backtest
